### PR TITLE
Added compatibility with Leaflet 1.0 branch

### PR DESCRIPTION
**Pull request by chugcup**
The Leaflet 1.0 release included a number of incompatible API changes that broke some features of Leaflet.draw (notably the edit features).
These include:

  1. Polylines and Polygons may now use nested Arrays of LatLng objects.
     These correspond to deprecated MultiPolygons containing multiple "rings"
     where the first Array is the outer ring and all subsequent rings are
     subtracted inner rings (e.g. donut).
  2. The Polygon.getLatLngs() method now always returns a nested array of rings.
  3. Removed Polyline/Polygon `spliceLatLngs` method (use `setLatLngs` instead).
  4. Removed LatLng `RAD_TO_DEG`, `DEG_TO_RAD`, and `MAX_MARGIN` constants.

Other relevant internal API changes include:

  5. Polyline._projectLatLngs() no longer sets `this._originalPoints` array.
     Instead, it expects for array to be passed in (by reference) for Point
     objects to be assigned to.
  6. L.Marker._initInteraction() was rewritten (copied verbatim in
     src/ext/TouchEvents.js file).

In this pull request I refactored the draw/edit classes to use feature-detection to determine if the Polygon/Polyline models follow the new format (1) and attempt to handle the LatLng arrays properly.  There were also a number of event issues related to editing Markers that I fixed, possibly due to bad merges.

With these changes the plugin should now be fully compatible with **both** the Leaflet 0.7.x and 1.0+ branches.  I tested using the existing 0.7.2 examples and the latest 1.0.0-rc3 release.

The examples have also be updated to use the latest Leaflet 1.0.0-rc3 release candidate.  I moved the previous examples to examples/0.7.x/ folder to help verify compatibility with both versions.

NOTE: The `dist/` contents have not been updated yet.

### CODE REVIEW

**Comment by chugcup** [comment]
One known issue I have encountered: when editing a Polygon/Polyline that is marked `allowIntersection=false` if you violate the intersection markers when editing, the map will lock up (with no error given).  This only happens when _editing_ a poly object (not when drawing a new one).

This appears to be an issue with event handlers on the map, but I haven't been able to track it down yet.  One thing to note is that I confirmed this bug was introduced in the Leaflet 1.0.0-rc2 release candidate; it does not appear to happen in the 1.0.0-beta or 1.0.0-rc1 releases.

**Comment by tomhughes** [comment]
There also seem to be problems if you try and call `bindTooltip` on a marker added with the draw plugin - it throws a TypeError exception I think because the `L.Tooltip` class defined by the plugin clashes with the one that leaflet itself now defines.

**Comment by chugcup** [comment]
OK, I have seen one or more forks rename this class to deconflict (e.g. `L.Draw.Tooltip`)

https://github.com/sigh71/Leaflet.draw/commit/915378e27d4294984ba7e3fd6aa309594bdaa06b

That appears to be a good solution so I may try to merge it in

**Comment by chugcup** [comment]
Included `L.Tooltip` rename in latest commit, and regenerated dist/

https://github.com/chugcup/Leaflet.draw/commit/93e6f968e622905f2b7793fec5e07bb5fa0888cb

**Comment by ddproxy** [comment]
Code review scheduled for this afternoon. A release will be made. 
Thanks @chugcup ;)

**Comment by jrandeniya** [comment]
I think we need to update the `bower.json` dependencies, it's pointing to `^0.7.0`

**Comment by ddproxy** [comment]
@chugcup @jrandeniya @plaxdan @antoine-giret @tomhughes -- #607 Contains these updates and slight changes to Readme, Breaking changes documents.

@jrandeniya -- 0.7.0 is still supported, I'm not familiar enough with bower to know if ^1.0.0 will still allow 0.7.0 in projects. If it's a non-issue, I'll change the bower in patch.

**This Pull Request will be closed with #607 merge**

**Pull request closed without merging**
