### PR TITLE
 [fix] issue when user cancel editing

### PR DESCRIPTION
**Pull request by SNtGog**

### CODE REVIEW

**Comment by KoTius** [comment]
Could you explain how does it work please?
this._poly.on('revert-edited', this._updateLatLngs, this);
As i can understand you add handler named "revert_eddited", which will call _updateLatLngs. But how or when the system calls it?

**Comment by SNtGog** [comment]
System fire this event in L.EditToolbar.Edit._revertLayer, after system replaced edited latlngs of layer to the unedited. 
When latlngs was replaced, need update _verticesHandlers of L.Edit.Poly. To do this, i simple re-create _verticesHandlers each time when user start editing.

**Comment by KoTius** [comment]
SNtGog thanks for reply mate.
May i ask you a question about other thing please?
Lets assume we've created a new poly. 
http://SSMaker.ru/3fef4637/
We've clicked edit, moved some hooks to edit,
http://SSMaker.ru/b19dbe62/
 then we click cancel. Poly is back to the original state, but the hooks, we moved didn't .
If we click edit again the hooks are dead :/
http://SSMaker.ru/9e644838/
Have you fixed that problem?
I will screen.
Sorry for the question and my english :)

**Comment by KoTius** [comment]
Oh sorry, that is a bug of the leaflet 0.3.0 version. 
In version 0.2.4 it was fine. I will post this to issues.

**Comment by SNtGog** [comment]
I fix it in 0.3.0. All I've done is this pull request.

**Pull request merged**
