### PR TITLE
Agrimap development

### PR DESCRIPTION
**Pull request by JamesMcIntosh**

### CODE REVIEW

**Comment by germanjoey** [comment]
Hello,

- Could you explain commit a7bfeae (turn off clickable etc). What does this do?

- For commit 7653f08 (revert on edit tool change), I think you need to fire an L.Draw.Event.CANCELED event, at the very least so that the UndoManager, from my PR from Saturaday, will know to clear those actions. In addition to edit mode, does switching out of delete mode also cause a revert?

**Comment by JamesMcIntosh** [comment]
Hi Joseph,

That pull request was a little premature (accidental), I'm just upgrading through to v1 and will see what is still relevant and repackage these into individual pull-requests around
* Improve definition of toolbar handlers state - available vs enabled
* Improve passing in of custom CSS classes per instance
* Enabling and disabling tooling using events - helpful when you have external actions / buttons in your UI
* Fix definition of Handler.type

In commit a7bfeae I turned off the click listeners when using 0.7 because there were cases where removing the click listener would propagate all the way down to the map and remove all click listeners on the map because the _onClick() function was null. It appears that this has been fixed in this Leaflet.
https://github.com/Leaflet/Leaflet/commit/c185cb59c4d838c66cd2daef2272acf31628a4f4

James

**Comment by ddproxy** [comment]
Thanks for keeping on top of this, and so quickly ;)

@JamesMcIntosh I'm curious where this is going.

**Comment by JamesMcIntosh** [comment]
Hi Jon, we are using Leaflet.draw in the web-version of www.agrimap.com

**Comment by ddproxy** [comment]
@JamesMcIntosh Would you mind reaching out to me at ddproxy@gmail.com?

**Pull request closed without merging**
