### PR TITLE
Fix draw polygons for mouse events on devices with touch screens - 2

### PR DESCRIPTION
**Pull request by B3nCr**
I created this pull request but it included a change that didn't want to be merged into the original project. https://github.com/Leaflet/Leaflet.draw/pull/636

Undoing the change would have broken my repo and the github.io page liked to it which is useful for testing the fix. Thus I have created a new branch and a new PR.

This PR resolves a few different issues.
https://github.com/Leaflet/Leaflet.draw/issues/631
https://github.com/Leaflet/Leaflet.draw/issues/637
https://github.com/Leaflet/Leaflet.draw/issues/624

This is my github.io page that shows the fix working. https://b3ncr.github.io/docs/examples/full.html

### CODE REVIEW

**Comment by B3nCr** [comment]
If this is getting merged to master do I need to add the build output to this commit?

**Comment by jbccollins** [comment]
Consider this comment my approval and +1 for what it's worth.

**Comment by DaveOke** [comment]
Here's another fix for the same problem we implemented in addVertex - also works in cases where the user accidentally adds two points in the same location:

addVertex: function (latlng) {
  var markersLength = this._markers.length;

  // If the last point clicked is identical to the this point, ignore it.
  // This works around a bug where we get an onClicked and an OnTouch event (IE11, touch screens) when adding a vertex.
  if (markersLength > 1) {
    if (latlng.equals(this._markers[this._markers.length - 1].getLatLng()))
      return;
  }

**Comment by z0d14c** [comment]
this is not fixed for me in the current **master**/**0.4.7** branches. I think possibly a regression has occurred, because the original fork of @B3nCr's branch did fix many issues for me, and the polyline file looks significantly different (particularly the `_onTouch` function). :\

**Comment by B3nCr** [comment]
There was another PR merged that fixed the same issue. I never tested their fix, I wonder if it overwrote my changes

**Comment by z0d14c** [comment]
@B3nCr yeah idk. i tried looking for your changes in the codebase and even the commit history for the polyline file, and was unable to, although it's possible I have a misconception of how github's interface works.

**Comment by B3nCr** [comment]
This was merged 4 days after my change. https://github.com/Leaflet/Leaflet.draw/pull/632/files

To be fair I always thought my change was a workaround and I've not tested that PR so I'm not 100% certain this was the issue but it's in the same area

**Comment by z0d14c** [comment]
Yeah, I'm pretty sure that regresses your fix, workaround or no, which basically renders IE/Android/iOS unusable for the respectively bugged draw shapes. I'll see if I can take a look at working on a PR this week as I'd like to continue using the main repo, but we'll see. @B3nCr

**Comment by B3nCr** [comment]
I guess this really needs more tests in that case as I assume both PRs passed all the existing tests. Could you write a test that fails?

**Pull request merged**
