### PR TITLE
Snapping

### PR DESCRIPTION
**Pull request by Starefossen**
Magnetic snapping capability to multiple features across multiple layers when drawing, and editing, polylines.

``` javascript
var drawControl = new L.Control.Draw({
    polyline: {
        shapeOptions: {
            snapping: {
                enabled: true,                  // enable snapping
                layers: [myLayer1,myLayer2],    // layers to snap to
                sensitivity: 20                 // sensitivity (in pixels)
            }
        }
    }
});
```

### CODE REVIEW

**Comment by ddproxy** [comment]
I like this! @leplatrem Is there anything we can add (or keep aware of) in Leaflet.draw going forward?

**Comment by leplatrem** [comment]
Hi @ddproxy! I am sorry I am disconnected from those projects in my new job... Maybe @fredericbonifas has an idea?

**Comment by fredericbonifas** [comment]
Hi @ddproxy and @leplatrem !

The problem remaining in Leaflet.Snap was the lack of snapping when drawing a new layer, but this works now as shown here: http://makinacorpus.github.io/Leaflet.Snap/
Would you like something else to be improved?

Best!

**Comment by ddproxy** [comment]
@makinacorpus @fredericbonifas There's an issue with snapping a polygon (line, in this example) to a new polygon.

https://github.com/makinacorpus/Leaflet.Snap/issues/22

- Draw a new polygon, close the loop
- Move the old (line) and try to snap to the new polygon
- No dice

**Comment by ddproxy** [comment]
Closing this PR. Suggesting use of Snap plugin for snapping functionality.

**Pull request closed without merging**
