### PR TITLE
bugfix, in touchmode map does not allow to draw Circle or Rectangle

### PR DESCRIPTION
**Pull request by vladimirbuskin**
... it stops right after start, when touchend fires.

i am not actually sure why

L.DomEvent.on(document, 'touchstart', L.DomEvent.preventDefault);

is not working, but line below helps

document.addEventListener('touchstart', L.DomEvent.preventDefault);

is that is Leaflet bug which prevents native events assignment, for touch events? Should we create an issue in Leaflet?

### CODE REVIEW

**Comment by vladimirbuskin** [comment]
fixes problem for new chrome

**Comment by ericbarch** [comment]
LGTM. Tested against Leaflet 1.0.3, Draw 0.4.9, and Chrome 58.0.3029.83 for Android.

**Comment by skalb** [comment]
I see the same issue in MS Edge on a Surface Pro--any ideas?

**Comment by ddproxy** [comment]
Sorry I've not been up to date on this as I should have been. @skalb is edge on pro erroneous with with this patch?

**Comment by skalb** [comment]
Correct, I suspect there may be a weird interaction with the Leaflet Map Draggable class.

I was able to successfully draw rectangles by:
1) disabling dragging on the map during initialization
2) leaving drag enabled while drawing

Clearly neither of those options would work in practice.

**Comment by germanjoey** [comment]
Cool. Is there any analogous fix for edit? (or was there ever a problem w/ touch with edit to begin with?)

**Comment by m314** [comment]
Bump.  Any updates on whether this pull request will be incorporated?

**Comment by dougshamoo** [comment]
@skalb Were you ever able to get this working in MS Edge on Surface Pro? We just ran across the same issue and I wanted to check before I get too far into it.

**Comment by skalb** [comment]
@dougshamoo No, I was not.

**Comment by m314** [comment]
@dougshamoo Can confirm this merge into master does not work with MS Edge. (I'm using MS Edge 40.15063.674.0 with a touch screen on Windows 10, on a desktop computer.)

I would be very interested if you make any progress on this!

**Pull request merged**
