### PR TITLE
Polyline fix

### PR DESCRIPTION
**Pull request by ddproxy**
Polyline fixes squashed from @z0d14c's branch

### CODE REVIEW

**Comment by ddproxy** [comment]
Bugs:
- When closing a polygon, the polylines can still cross, but still an improvement
- Using chrome device toolbar (ipad mode) the touch events will fire twice and not allow a polyline to be continued (so it's a segment)

**Comment by ddproxy** [comment]
@z0d14c - If we can get the second bug resolved (and I don't find any other showstoppers) I can merge this PR and close the previous one.

**Comment by z0d14c** [comment]
@ddproxy kk ill be looking into this this week

**Comment by z0d14c** [comment]
I havent got a chance to look at this due to the holidays being crazier than expected. I'll be freeing up in the latter half of this week, though, hopefully.

**Comment by ddproxy** [comment]
@z0d14c It's fine, needed roll out what fixes are available now. I'll be back on duty soon too.

**Comment by formigarafa** [comment]
hello there,

I have found a workaround to draw polylines on touch devices. I just delayed the addition of the finish handler on the last marker.

```
var originalPolylineClass = L.Draw.Polyline;
L.Draw.Polyline = originalPolylineClass.extend({
  _updateFinishHandler: function () {
    var markerCount = this._markers.length;
    // The last marker should have a click handler to close the polyline
    if (markerCount > 1) {
      setTimeout(function() {
        this._markers[markerCount - 1].on('click', this._finishShape, this);
      }.bind(this), 50);
    }

    // Remove the old marker click handler (as only the last point should close the polyline)
    if (markerCount > 2) {
      this._markers[markerCount - 2].off('click', this._finishShape, this);
    }
  },
});

```

**Pull request merged**
