### PR TITLE
Make Draw Polyline Work On Chrome For Touch+Mouse Devices

### PR DESCRIPTION
**Pull request by arottersman**
- When drawing PolyLine vertices in Chrome on a device that supports both touch and mouse inputs
       - clicking the mouse would call both the touch and mouse events and create two vertices at once
       - you would be unable to close the PolyLine shape while using the mouse
- To fix draw polyline:
  - Store last time the mouse up handler fired
  - Check that more than 10ms have passed since the mouseUp handler fired when the onTouch handler tries to call it
  - This way if a mouse in a touch browser has already fired mouseUp, it won't fire again

Connects #548

### CODE REVIEW

**Comment by baikon** [comment]
@arottersman why was this closed?

**Comment by arottersman** [comment]
@baikon - We decided to use our own fork for the project (https://github.com/azavea/Leaflet.draw)

Would be happy to reopen if anyone thinks this would be useful!

**Comment by baikon** [comment]
Cool! Is there anything else on this fork other than the updates on this pull request?

**Comment by arottersman** [comment]
Yeah, the azavea fork is actual a fork of michaelguild13/Leaflet.draw, and in addition to the one fixing the touch device issue, there's a commit that makes the draw vertices big. You could cherrypick the Draw Polyline fix though

**Comment by baikon** [comment]
@arottersman just to be clear, this doesn't fix the touch event though does it? just makes it work with click?

**Comment by arottersman** [comment]
@baikon We were having the issue described here: https://github.com/WikiWatershed/model-my-watershed/issues/1190 - where we could close polyline's on touch devices just fine, but if a device was running chrome and had touch and mouse capabilities, we couldn't close the shape with a mouse.

Do touch events not work for you?

**Comment by baikon** [comment]
@arottersman ah, it looks like my issue is when browser has both touch and mouse capabilities, the issue is repro'd where the initial touch or mouse event will fire two events so it actually enables the tool and then clicks the first vertex right away.

**Comment by baikon** [comment]
@arottersman i think the polyline tool will work with touch events if i can get this part sorted out. i need to complete the shape after counting how many vertexes were added to the map:

```
map.on('draw:drawvertex', function(e) {
      if (Object.keys(e.layers._layers).length > 1) {
        // need to close polyline here
      }
});
```

would you have any ideas or suggestions on how to do that?

**Pull request closed without merging**
