### PR TITLE
Added hole editing support to polygons with holes.

### PR DESCRIPTION
**Pull request by WillFM**

### CODE REVIEW

**Comment by sbharadwaj92** [comment]
can anyone explain me how to draw holes inside polygon using leaflet draw?

**Comment by ddproxy** [comment]
Need to add documentation for this @WillFM

**Comment by WillFM** [comment]
@ddproxy, Ohh gosh, I wrote this almost 3 years ago. I'm not sure it really needed documentation. Previously if you had a polygon with holes, it wouldn't allow you to edit the hole inside the polygon, all this did was add the editing vertices, so you could manipulate the hole as well. I've not used leaflet in some time now. the issue this was addressing may have already been resolved by Leaflet?

**Comment by ddproxy** [comment]
I see, I'll double check that it works properly now. If not, this PR may still apply ;)

**Comment by asb-orra** [comment]
+1

**Comment by kragoth** [comment]
I had to get hole editing working for my project. This pull request was very instrumental in helping me get it working. Thanks @WillFM.

I have not put together a pull request or updated this branch yet as this took me nearly 2 days to get everything working and I really need to get my work finished!

But, I did all my changes in jsfiddle so you can see them here.
https://jsfiddle.net/onu856hn/21/

This was working with:
leaflet 1.0.2
leaflet.draw 0.4.9
leaflet.snap (no version info in file, see jsfiddle)

I didn't have to change a lot from this pull request but, I did make a few changes.

**Comment by Wasseing** [comment]
Am i late folks ? I am still having this issue, i tried your patch @kragoth but it does not work either.

``` 
"leaflet": "^1.6.0",
"leaflet-draw": "^1.0.4",
```
uneditable inner rings

**Pull request closed without merging**
