### PR TITLE
refs #714. L.CircleMarker can be edited and drawed for leaflet 1.0.3

### PR DESCRIPTION
**Pull request by fpuga**
As `Circle` inherits from `CircleMarker` my first try was to create a `Draw.CircleMarker` class as parent of `Draw.Circle`. But as most of the needed functionality was already present in `Draw.Marker` and commonly `CircleMarker` as expected to behave like "markers without icons", finally a make `Draw.CircleMarker` a child of `Draw.Marker`.

Then I tried to make `Edit.CircleMarker` a child of `Edit.Marker`, but `CircleMarker` is not "draggable", so some errors arise when trying to use an implementation that relies on marker/draggable capabilities like

```
L.Edit.CircleMarker = L.Edit.Marker.extend({

});

L.CircleMarker.addInitHook(function () {
	if (L.Edit.CircleMarker) {
		this.editing = new L.Edit.CircleMarker(this);

		if (this.options.editable) {
			this.editing.enable();
		}
	}
});
```

Just to have some working code and open up the discussion I implement `Edit.CircleMarker` as a parent of `Edit.Circle` following the hierarchy of Leaflet.

So this is working but there are some caveats:

* An icon for the draw toolbar for circlemarker is needed. Now is using the same as marker, but probably it makes sense to create a new one based on circle (for example with the center of the circle empty)

* The actual hierarchy does not have so much sense, Edit and Draw should follow the same hierarchy, or just be created as independed. ¿Any idea here?

### CODE REVIEW

**Comment by v1r0x** [comment]
Thanks for working on this! I built Leaflet.draw myself (as you described in #714). The minified version doesn't work (it only contains `undefined`), but `leaflet.draw-src.js` works fine. Thanks!

Your caveats:
1. I don't know if a separate control icon for circle marker is needed. We only use CircleMarker in the `pointToLayer` method. Additionally there was no control icon for CircleMarker in the official releases. Thus I think you ignore this.
2. I'm not really into the Leaflet structure, maybe someone with more knowledge of leaflet can help you.

**Comment by fpuga** [comment]
Thanks for your comments. Glad it works for you.

I haven't work with jake previously so I don't know how the dist is created, I just copy&paste the README instructions :)

I hope that some of the Leaflet.Draw committers have time to review the PR and suggest how to improve it to be merged.

**Comment by v1r0x** [comment]
@ddproxy Could you help here or push me or @fpuga in the right direction or what it needs to be merged?
In our project we rely on bower packages, so self-compiling and cherrypicking is not a satisfying option. Since we really need this feature I'm willing to help.

It's sad to see all these great contributions, which seem to be ignored. I completly understand if people don't have much time, but _please_ leave a short message to indicate that working on these PRs is not a complete waste of time.

**Comment by ddproxy** [comment]
I think this is fine, I would just like to have a different icon for the circle marker.

**Comment by fpuga** [comment]
@ddproxy @v1r0x Thanks for taking a look at this. I push another commit with an icon.

I have not worked before with sprites, neither have many experience with inkspace. Let me know if it's good for you or some change is needed.

**Comment by v1r0x** [comment]
@fpuga thanks for fixing it! Icon itself looks good to me, but I think it is wider than the other icons. The old `.svg` was 540px and 9 icons (= 60px per icon), the new one added one icon, but 70px instead of 60px. Same for the smaller version (30px vs. 35px). I know this is nitpicking :wink: 
Other stuff looks good so far! Happy to see this is going on :)

**Comment by fpuga** [comment]
Thanks for the review. I think is fixed now. Just let me know if more changes are needed.

I can open a new branch/pr if you want to avoid noise in the commits.

**Comment by v1r0x** [comment]
Thanks again! One thing I didn't see yesterday, unfortunately. The added icon is a bit darker than the other icons. Would be nice to have them all in the same color.

> I can open a new branch/pr if you want to avoid noise in the commits.

You can squash your commits to combine them. Run `git rebase -i ba620f69dddb82f303558f76ffc8e73daa482be9`. The ID after `-i` is the commit ID of the commit **before** the commits you want to squash. Then you can pick the first commit (`8f8242f8a6919ded85a242dc594e3ed54a9ade15`) and squash the other icon related commits (`53aff4fc3cc1067d2e82775fb0c4064c4d6feb8f` and maybe others) on it.

**Comment by fpuga** [comment]
I hope that now it's correct. I neither catch that the colour was different. Sorry for the inconvenience. Don't hesitate to ask for more changes if you think that are needed. I rebase the branch against the actual master to make the merge easies.

**Comment by v1r0x** [comment]
Looks good! No more change requests from my side 😉

**Comment by v1r0x** [comment]
Ok to merge @ddproxy ?

**Comment by ddproxy** [comment]
👍 Slick

**Comment by fpuga** [comment]
Thanks to both

**Comment by brunob** [comment]
@fpuga circlemarker should also be added to the doc here https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#drawoptions

**Pull request merged**
